name: CI

on:
  push:
    branches: [ 💫 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install --no-save

      - name: clear gitignore
        run: |
          sed -i '/node_modules/d' .gitignore
          rm -rf .git

      - name: deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: release
          build_dir: .
          commit_message: Deploy for deno usage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
