name: deno

on:
  push:
    branches: [ 💫 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: fmt
        run: deno fmt --check

      - name: lint
        run: deno lint --unstable